CREATE TABLE direct_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    client_message_id uuid NOT NULL,
    body varchar(2000) NOT NULL CHECK (length(trim(body)) > 0),
    sent_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT direct_messages_not_self CHECK (sender_id <> recipient_id),
    UNIQUE (sender_id, client_message_id)
);
CREATE INDEX direct_messages_sender ON direct_messages(sender_id, id DESC);
CREATE INDEX direct_messages_recipient ON direct_messages(recipient_id, id DESC);
