// Riot Games Data Dragon, pinned to the verified Korean realm on 2026-09-14.
// Source: https://developer.riotgames.com/docs/lol#data-dragon
// Version: https://ddragon.leagueoflegends.com/realms/kr.json
// Catalogs: https://ddragon.leagueoflegends.com/cdn/16.18.1/data/{ko_KR,en_US}/champion.json
// Each tuple is [Data Dragon ID, Korean name, English name, portrait filename].
export const CHAMPION_CATALOG = [
  ["Aatrox", "아트록스", "Aatrox", "Aatrox.png"],
  ["Ahri", "아리", "Ahri", "Ahri.png"],
  ["Akali", "아칼리", "Akali", "Akali.png"],
  ["Akshan", "아크샨", "Akshan", "Akshan.png"],
  ["Alistar", "알리스타", "Alistar", "Alistar.png"],
  ["Ambessa", "암베사", "Ambessa", "Ambessa.png"],
  ["Amumu", "아무무", "Amumu", "Amumu.png"],
  ["Anivia", "애니비아", "Anivia", "Anivia.png"],
  ["Annie", "애니", "Annie", "Annie.png"],
  ["Aphelios", "아펠리오스", "Aphelios", "Aphelios.png"],
  ["Ashe", "애쉬", "Ashe", "Ashe.png"],
  ["AurelionSol", "아우렐리온 솔", "Aurelion Sol", "AurelionSol.png"],
  ["Aurora", "오로라", "Aurora", "Aurora.png"],
  ["Azir", "아지르", "Azir", "Azir.png"],
  ["Bard", "바드", "Bard", "Bard.png"],
  ["Belveth", "벨베스", "Bel'Veth", "Belveth.png"],
  ["Blitzcrank", "블리츠크랭크", "Blitzcrank", "Blitzcrank.png"],
  ["Brand", "브랜드", "Brand", "Brand.png"],
  ["Braum", "브라움", "Braum", "Braum.png"],
  ["Briar", "브라이어", "Briar", "Briar.png"],
  ["Caitlyn", "케이틀린", "Caitlyn", "Caitlyn.png"],
  ["Camille", "카밀", "Camille", "Camille.png"],
  ["Cassiopeia", "카시오페아", "Cassiopeia", "Cassiopeia.png"],
  ["Chogath", "초가스", "Cho'Gath", "Chogath.png"],
  ["Corki", "코르키", "Corki", "Corki.png"],
  ["Darius", "다리우스", "Darius", "Darius.png"],
  ["Diana", "다이애나", "Diana", "Diana.png"],
  ["Draven", "드레이븐", "Draven", "Draven.png"],
  ["DrMundo", "문도 박사", "Dr. Mundo", "DrMundo.png"],
  ["Ekko", "에코", "Ekko", "Ekko.png"],
  ["Elise", "엘리스", "Elise", "Elise.png"],
  ["Evelynn", "이블린", "Evelynn", "Evelynn.png"],
  ["Ezreal", "이즈리얼", "Ezreal", "Ezreal.png"],
  ["Fiddlesticks", "피들스틱", "Fiddlesticks", "Fiddlesticks.png"],
  ["Fiora", "피오라", "Fiora", "Fiora.png"],
  ["Fizz", "피즈", "Fizz", "Fizz.png"],
  ["Galio", "갈리오", "Galio", "Galio.png"],
  ["Gangplank", "갱플랭크", "Gangplank", "Gangplank.png"],
  ["Garen", "가렌", "Garen", "Garen.png"],
  ["Gnar", "나르", "Gnar", "Gnar.png"],
  ["Gragas", "그라가스", "Gragas", "Gragas.png"],
  ["Graves", "그레이브즈", "Graves", "Graves.png"],
  ["Gwen", "그웬", "Gwen", "Gwen.png"],
  ["Hecarim", "헤카림", "Hecarim", "Hecarim.png"],
  ["Heimerdinger", "하이머딩거", "Heimerdinger", "Heimerdinger.png"],
  ["Hwei", "흐웨이", "Hwei", "Hwei.png"],
  ["Illaoi", "일라오이", "Illaoi", "Illaoi.png"],
  ["Irelia", "이렐리아", "Irelia", "Irelia.png"],
  ["Ivern", "아이번", "Ivern", "Ivern.png"],
  ["Janna", "잔나", "Janna", "Janna.png"],
  ["JarvanIV", "자르반 4세", "Jarvan IV", "JarvanIV.png"],
  ["Jax", "잭스", "Jax", "Jax.png"],
  ["Jayce", "제이스", "Jayce", "Jayce.png"],
  ["Jhin", "진", "Jhin", "Jhin.png"],
  ["Jinx", "징크스", "Jinx", "Jinx.png"],
  ["Kaisa", "카이사", "Kai'Sa", "Kaisa.png"],
  ["Kalista", "칼리스타", "Kalista", "Kalista.png"],
  ["Karma", "카르마", "Karma", "Karma.png"],
  ["Karthus", "카서스", "Karthus", "Karthus.png"],
  ["Kassadin", "카사딘", "Kassadin", "Kassadin.png"],
  ["Katarina", "카타리나", "Katarina", "Katarina.png"],
  ["Kayle", "케일", "Kayle", "Kayle.png"],
  ["Kayn", "케인", "Kayn", "Kayn.png"],
  ["Kennen", "케넨", "Kennen", "Kennen.png"],
  ["Khazix", "카직스", "Kha'Zix", "Khazix.png"],
  ["Kindred", "킨드레드", "Kindred", "Kindred.png"],
  ["Kled", "클레드", "Kled", "Kled.png"],
  ["KogMaw", "코그모", "Kog'Maw", "KogMaw.png"],
  ["KSante", "크산테", "K'Sante", "KSante.png"],
  ["Leblanc", "르블랑", "LeBlanc", "Leblanc.png"],
  ["LeeSin", "리 신", "Lee Sin", "LeeSin.png"],
  ["Leona", "레오나", "Leona", "Leona.png"],
  ["Lillia", "릴리아", "Lillia", "Lillia.png"],
  ["Lissandra", "리산드라", "Lissandra", "Lissandra.png"],
  ["Locke", "로크", "Locke", "Locke.png"],
  ["Lucian", "루시안", "Lucian", "Lucian.png"],
  ["Lulu", "룰루", "Lulu", "Lulu.png"],
  ["Lux", "럭스", "Lux", "Lux.png"],
  ["Malphite", "말파이트", "Malphite", "Malphite.png"],
  ["Malzahar", "말자하", "Malzahar", "Malzahar.png"],
  ["Maokai", "마오카이", "Maokai", "Maokai.png"],
  ["MasterYi", "마스터 이", "Master Yi", "MasterYi.png"],
  ["Mel", "멜", "Mel", "Mel.png"],
  ["Milio", "밀리오", "Milio", "Milio.png"],
  ["MissFortune", "미스 포츈", "Miss Fortune", "MissFortune.png"],
  ["MonkeyKing", "오공", "Wukong", "MonkeyKing.png"],
  ["Mordekaiser", "모데카이저", "Mordekaiser", "Mordekaiser.png"],
  ["Morgana", "모르가나", "Morgana", "Morgana.png"],
  ["Naafiri", "나피리", "Naafiri", "Naafiri.png"],
  ["Nami", "나미", "Nami", "Nami.png"],
  ["Nasus", "나서스", "Nasus", "Nasus.png"],
  ["Nautilus", "노틸러스", "Nautilus", "Nautilus.png"],
  ["Neeko", "니코", "Neeko", "Neeko.png"],
  ["Nidalee", "니달리", "Nidalee", "Nidalee.png"],
  ["Nilah", "닐라", "Nilah", "Nilah.png"],
  ["Nocturne", "녹턴", "Nocturne", "Nocturne.png"],
  ["Nunu", "누누와 윌럼프", "Nunu & Willump", "Nunu.png"],
  ["Olaf", "올라프", "Olaf", "Olaf.png"],
  ["Orianna", "오리아나", "Orianna", "Orianna.png"],
  ["Ornn", "오른", "Ornn", "Ornn.png"],
  ["Pantheon", "판테온", "Pantheon", "Pantheon.png"],
  ["Poppy", "뽀삐", "Poppy", "Poppy.png"],
  ["Pyke", "파이크", "Pyke", "Pyke.png"],
  ["Qiyana", "키아나", "Qiyana", "Qiyana.png"],
  ["Quinn", "퀸", "Quinn", "Quinn.png"],
  ["Rakan", "라칸", "Rakan", "Rakan.png"],
  ["Rammus", "람머스", "Rammus", "Rammus.png"],
  ["RekSai", "렉사이", "Rek'Sai", "RekSai.png"],
  ["Rell", "렐", "Rell", "Rell.png"],
  ["Renata", "레나타 글라스크", "Renata Glasc", "Renata.png"],
  ["Renekton", "레넥톤", "Renekton", "Renekton.png"],
  ["Rengar", "렝가", "Rengar", "Rengar.png"],
  ["Riven", "리븐", "Riven", "Riven.png"],
  ["Rumble", "럼블", "Rumble", "Rumble.png"],
  ["Ryze", "라이즈", "Ryze", "Ryze.png"],
  ["Samira", "사미라", "Samira", "Samira.png"],
  ["Sejuani", "세주아니", "Sejuani", "Sejuani.png"],
  ["Senna", "세나", "Senna", "Senna.png"],
  ["Seraphine", "세라핀", "Seraphine", "Seraphine.png"],
  ["Sett", "세트", "Sett", "Sett.png"],
  ["Shaco", "샤코", "Shaco", "Shaco.png"],
  ["Shen", "쉔", "Shen", "Shen.png"],
  ["Shyvana", "쉬바나", "Shyvana", "Shyvana.png"],
  ["Singed", "신지드", "Singed", "Singed.png"],
  ["Sion", "사이온", "Sion", "Sion.png"],
  ["Sivir", "시비르", "Sivir", "Sivir.png"],
  ["Skarner", "스카너", "Skarner", "Skarner.png"],
  ["Smolder", "스몰더", "Smolder", "Smolder.png"],
  ["Sona", "소나", "Sona", "Sona.png"],
  ["Soraka", "소라카", "Soraka", "Soraka.png"],
  ["Swain", "스웨인", "Swain", "Swain.png"],
  ["Sylas", "사일러스", "Sylas", "Sylas.png"],
  ["Syndra", "신드라", "Syndra", "Syndra.png"],
  ["TahmKench", "탐 켄치", "Tahm Kench", "TahmKench.png"],
  ["Taliyah", "탈리야", "Taliyah", "Taliyah.png"],
  ["Talon", "탈론", "Talon", "Talon.png"],
  ["Taric", "타릭", "Taric", "Taric.png"],
  ["Teemo", "티모", "Teemo", "Teemo.png"],
  ["Thresh", "쓰레쉬", "Thresh", "Thresh.png"],
  ["Tristana", "트리스타나", "Tristana", "Tristana.png"],
  ["Trundle", "트런들", "Trundle", "Trundle.png"],
  ["Tryndamere", "트린다미어", "Tryndamere", "Tryndamere.png"],
  ["TwistedFate", "트위스티드 페이트", "Twisted Fate", "TwistedFate.png"],
  ["Twitch", "트위치", "Twitch", "Twitch.png"],
  ["Udyr", "우디르", "Udyr", "Udyr.png"],
  ["Urgot", "우르곳", "Urgot", "Urgot.png"],
  ["Varus", "바루스", "Varus", "Varus.png"],
  ["Vayne", "베인", "Vayne", "Vayne.png"],
  ["Veigar", "베이가", "Veigar", "Veigar.png"],
  ["Velkoz", "벨코즈", "Vel'Koz", "Velkoz.png"],
  ["Vex", "벡스", "Vex", "Vex.png"],
  ["Vi", "바이", "Vi", "Vi.png"],
  ["Viego", "비에고", "Viego", "Viego.png"],
  ["Viktor", "빅토르", "Viktor", "Viktor.png"],
  ["Vladimir", "블라디미르", "Vladimir", "Vladimir.png"],
  ["Volibear", "볼리베어", "Volibear", "Volibear.png"],
  ["Warwick", "워윅", "Warwick", "Warwick.png"],
  ["Xayah", "자야", "Xayah", "Xayah.png"],
  ["Xerath", "제라스", "Xerath", "Xerath.png"],
  ["XinZhao", "신 짜오", "Xin Zhao", "XinZhao.png"],
  ["Yasuo", "야스오", "Yasuo", "Yasuo.png"],
  ["Yone", "요네", "Yone", "Yone.png"],
  ["Yorick", "요릭", "Yorick", "Yorick.png"],
  ["Yunara", "유나라", "Yunara", "Yunara.png"],
  ["Yuumi", "유미", "Yuumi", "Yuumi.png"],
  ["Zaahen", "자헨", "Zaahen", "Zaahen.png"],
  ["Zac", "자크", "Zac", "Zac.png"],
  ["Zed", "제드", "Zed", "Zed.png"],
  ["Zeri", "제리", "Zeri", "Zeri.png"],
  ["Ziggs", "직스", "Ziggs", "Ziggs.png"],
  ["Zilean", "질리언", "Zilean", "Zilean.png"],
  ["Zoe", "조이", "Zoe", "Zoe.png"],
  ["Zyra", "자이라", "Zyra", "Zyra.png"],
] as const;
