-- 기준 마이그레이션 — 일부러 비워 두었다. 실행되는 SQL 이 한 줄도 없다.
--
-- Flyway 가 돌고 기록 테이블(flyway_schema_history)이 생기는 것까지만 확인하려는 파일이다.
-- 스키마도 테이블도 만들지 않는다 — 이 앱이 소유하는 스키마의 이름(account · party · social)은 정해졌지만
-- 테이블 컬럼과 DB 롤/GRANT 는 정해지지 않았다 (CLAUDE.md §3.5 · §7 "테이블 컬럼, DB 롤"). 지어내지 않는다.
--
-- 다음 마이그레이션부터는 스키마별 폴더에 둔다 — db/migration/<schema>/ (docs/11 #17 · CLAUDE.md §3.5).
--   · Flyway 는 하위 폴더까지 훑고, 버전 번호(V2, V3 …)는 폴더가 달라도 전체에서 하나뿐이어야 한다
--   · reservation 스키마의 마이그레이션은 여기 넣지 않는다 (CLAUDE.md §7 "reservation 스키마의 마이그레이션")
--   · 이미 적용된 마이그레이션 파일은 고치지 않는다(체크섬이 달라져 기동이 막힌다). 바꿀 것은 새 버전으로 쓴다
--
-- 이미 정해져 있어 그대로 따라야 하는 것 하나 — social.blocks 의 모양과 matching 롤의 SELECT 권한 (CLAUDE.md §3.5 · docs/11 D-1 · D-4).
