import { expect, test } from './support/fixtures';
import { createPost, enter, lolPost, uniqueTitle, type Post } from './support/domain';

test('방 설정 실제 저장·상대 동기화·권한, 수동 마감 취소·확정', async ({ crew }) => {
  const a = await crew.user('a'); const b = await crew.user('b'); const c = await crew.user('c');
  const title = uniqueTitle('settings-close');
  const body = lolPost(title, { allowAutoJoin: false });
  const room = await createPost(a, body);
  const id = room.postId;
  const host = await crew.appPage('a', `/app/party/${id}`);
  const close = host.getByRole('button', { name: '모집 마감', exact: true });
  await expect(close).toBeDisabled();
  expect((await enter(b, String(id), 'TOP')).status).toBe(201);
  const member = await crew.appPage('b', `/app/party/${id}`);
  await expect(member.getByRole('button', { name: '방 설정', exact: true })).toHaveCount(0);
  expect((await b.patch(`/posts/${id}`, { ...body, title: '권한 없는 수정' })).status).toBe(403);
  await host.getByRole('button', { name: '방 설정', exact: true }).click();
  const settings = host.getByRole('dialog', { name: '방 설정', exact: true });
  await expect(settings.getByRole('textbox', { name: '방 제목' })).toHaveValue(title);
  const changed = uniqueTitle('settings-saved');
  await settings.getByRole('textbox', { name: '방 제목' }).fill(changed);
  await settings.getByRole('button', { name: '변경사항 저장', exact: true }).click();
  await expect(settings).toHaveCount(0);
  const memberRoom = member.getByRole('region', { name: '방', exact: true });
  await expect(memberRoom.getByRole('heading', { name: changed, exact: true })).toBeVisible();
  const saved = await a.get<Post & { autoConfirmAt: string | null; autoConfirmWarningAt: string | null }>(`/posts/${id}`);
  expect(saved.body.title).toBe(changed);
  expect(saved.body.autoConfirmAt).toBeNull();
  expect(saved.body.autoConfirmWarningAt).toBeNull();
  await close.click();
  const confirm = host.getByRole('dialog', { name: '모집을 마감할까요?', exact: true });
  await confirm.getByRole('button', { name: '취소', exact: true }).click();
  expect((await a.get<Post>(`/posts/${id}`)).body.status).toBe('RECRUITING');
  await close.click();
  await confirm.getByRole('button', { name: '모집 마감', exact: true }).click();
  await expect(confirm).toHaveCount(0);
  await expect(close).toHaveCount(0);
  expect((await a.get<Post>(`/posts/${id}`)).body.status).toBe('CONFIRMED');
  expect((await enter(c, String(id), 'JUNGLE')).status).toBe(409);
  await expect(memberRoom.getByRole('log', { name: '방 메시지', exact: true })).toHaveCount(1);
  const text = uniqueTitle('마감 후에도 대화');
  const hostRoom = host.getByRole('region', { name: '방', exact: true });
  await expect(hostRoom.getByRole('button', { name: '메시지 보내기', exact: true })).toHaveCount(0);
  await hostRoom.getByRole('textbox', { name: '방에 메시지 보내기' }).fill(text);
  await hostRoom.getByRole('button', { name: '메시지 보내기', exact: true }).click();
  await expect(memberRoom.getByRole('log', { name: '방 메시지', exact: true }).getByText(text, { exact: true })).toBeVisible();
  await host.reload();
  await expect(host.getByRole('region', { name: '방', exact: true }).getByRole('heading', { name: changed, exact: true })).toBeVisible();
});
